shared:
  max_epoch: 20 #
  enable_dict:
    acc: true
    loss: true
    model: true
    val: true
    test: true
  quick_calc: true
monitor:
  classArgs:
    report:
      intermediate_default: val_acc
      final_default: val_acc
assessor:
  classArgs:
    basic:
      start_step_float: 0.0
      end_step_float: 0.5
      symptom_name_list: [ "VG","EG","DR","SC","HO","NMG","OF" ]
    compare:
      cmp_mode: minimize
      cmp_percent: 10 ###
      min_cmp_num: 10 
    diagnose:
      p_eg1: 10000
      p_eg2: 1000
      p_vg1: 0.00001
      p_vg2: 0.0001
      p_dr1: 0.5
      p_sc1: 0.0001
      p_sc2: 0.5
      p_ho1: 0.01
      p_ho2: 0.2
      p_of: 0
      wd_ho: 6
      wd_nmg: 6


















